version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - DATABASE_URL=postgresql://postgres:password@db:5432/mpls_db
      - SECRET_KEY=your-super-secret-key-for-production
    depends_on:
      - db
    volumes:
      - media_volume:/app/media

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=mpls_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - media_volume:/app/media
    depends_on:
      - web

volumes:
  postgres_data:
  media_volume:
