# Generated by Django 5.2.4 on 2025-07-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panitia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='urutan',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
