# Generated by Django 5.2.4 on 2025-07-11 17:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panitia', '0002_agenda_urutan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keuangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keterangan', models.CharField(max_length=255)),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=12)),
                ('jenis', models.CharField(choices=[('masuk', 'Pemasukan'), ('keluar', 'Pengeluaran')], max_length=10)),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
