# Generated by Django 5.2.4 on 2025-07-13 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panitia', '0003_keuangan'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarangLogistik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jumlah', models.PositiveIntegerField(default=0)),
                ('keterangan', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='CatatanKeuangan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('keterangan', models.CharField(max_length=255)),
                ('tipe', models.CharField(choices=[('masuk', 'Pemasukan'), ('keluar', 'Pengeluaran')], max_length=10)),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=12)),
                ('catatan', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LaranganBarang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('keterangan', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuIPM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pengumuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('isi', models.TextField()),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='kelompok',
            name='pelaksana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kelompok_pelaksana', to='panitia.anggota'),
        ),
    ]
