# Generated by Django 5.2.4 on 2025-07-13 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panitia', '0004_baranglogistik_catatankeuangan_laranganbarang_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panitia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabatan', models.CharField(max_length=100)),
                ('anggota', models.TextField(blank=True)),
                ('kedudukan', models.IntegerField(default=1)),
            ],
        ),
    ]
