# Generated by Django 5.2.4 on 2025-07-13 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panitia', '0005_panitia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AksesMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(max_length=50)),
                ('bisa_lihat', models.BooleanField(default=False)),
                ('bisa_edit', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='BarangLogistik',
        ),
        migrations.DeleteModel(
            name='CatatanKeuangan',
        ),
        migrations.DeleteModel(
            name='LaranganBarang',
        ),
        migrations.DeleteModel(
            name='MenuIPM',
        ),
        migrations.DeleteModel(
            name='Panitia',
        ),
        migrations.DeleteModel(
            name='Pengumuman',
        ),
        migrations.RemoveField(
            model_name='kelompok',
            name='pelaksana',
        ),
    ]
