# Generated by Django 5.2.4 on 2025-07-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panitia', '0006_aksesmenu_delete_baranglogistik_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(choices=[('Panitia Utama', 'Panitia Utama'), ('Panitia IPM', 'Panitia IPM'), ('Daftar Kelompok', 'Daftar Kelompok'), ('Pengumuman', 'Pengumuman'), ('Logistik', 'Logistik'), ('Surat-surat', 'Surat-surat'), ('Jadwal Kegiatan', 'Jadwal Kegiatan'), ('Absensi', 'Absensi'), ('Keuangan', 'Keuangan')], max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='aksesmenu',
            name='menu',
        ),
        migrations.AddField(
            model_name='aksesmenu',
            name='menu',
            field=models.ManyToManyField(to='panitia.menu'),
        ),
    ]
