# Generated by Django 5.2.4 on 2025-07-13 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panitia', '0007_menu_remove_aksesmenu_menu_aksesmenu_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aksesmenu',
            name='menu',
        ),
        migrations.AddField(
            model_name='aksesmenu',
            name='menu',
            field=models.CharField(choices=[('Panitia Utama', 'Panitia Utama'), ('Panitia IPM', 'Panitia IPM'), ('Daftar Kelompok', 'Daftar Kelompok'), ('Pengumuman', 'Pengumuman'), ('Logistik', 'Logistik'), ('Surat-surat', 'Surat-surat'), ('Jadwal Kegiatan', 'Jadwal Kegiatan'), ('Absensi', 'Absensi'), ('Keuangan', 'Keuangan')], default='Panitia Utama', max_length=50),
            preserve_default=False,
        ),
    ]
