# Generated by Django 5.2.4 on 2025-07-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panitia', '0008_remove_aksesmenu_menu_aksesmenu_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanitiaPelaksana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabatan', models.CharField(max_length=100)),
                ('anggota', models.TextField(help_text='Masukkan satu nama per baris')),
                ('kedudukan', models.PositiveIntegerField(default=99)),
            ],
        ),
        migrations.CreateModel(
            name='TugasUpacara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabatan', models.CharField(max_length=100)),
                ('tugas', models.TextField()),
                ('selesai', models.BooleanField(default=False)),
            ],
        ),
    ]
