# Generated by Django 5.2.4 on 2025-07-13 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panitia', '0009_panitiapelaksana_tugasupacara'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengumuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('isi', models.TextField()),
                ('waktu', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
