# Generated by Django 5.2.4 on 2025-07-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panitia', '0010_pengumuman'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarangLogistik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jumlah', models.PositiveIntegerField(default=1)),
                ('jenis', models.CharField(choices=[('pribadi', 'Pribadi'), ('kelompok', 'Kelompok')], max_length=10)),
                ('keterangan', models.TextField(blank=True)),
                ('waktu', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
