# Generated by Django 5.2.4 on 2025-07-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panitia', '0011_baranglogistik'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaranganBarang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('waktu', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='baranglogistik',
            name='jenis',
        ),
        migrations.RemoveField(
            model_name='baranglogistik',
            name='keterangan',
        ),
    ]
