# Generated by Django 5.2.4 on 2025-07-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panitia', '0012_laranganbarang_remove_baranglogistik_jenis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baranglogistik',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='laranganbarang',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
