# Generated by Django 5.2.4 on 2025-07-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panitia', '0013_alter_baranglogistik_id_alter_laranganbarang_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='baranglogistik',
            name='jenis',
            field=models.CharField(choices=[('pribadi', 'Pribadi'), ('kelompok', 'Kelompok')], default='umum', max_length=20),
            preserve_default=False,
        ),
    ]
