# Generated by Django 5.2.4 on 2025-07-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panitia', '0014_baranglogistik_jenis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aksesmenu',
            name='menu',
            field=models.CharField(choices=[('Panitia Utama', 'Panitia Utama'), ('Panitia IPM', 'Panitia IPM'), ('Koordinator Kelompok', 'Koordinator Kelompok'), ('Petugas Upacara', 'Petugas Upacara'), ('Panitia Pelaksana', 'Panitia Pelaksana'), ('Daftar Kelompok', 'Daftar Kelompok'), ('Pengumuman', 'Pengumuman'), ('Logistik', 'Logistik'), ('Surat-surat', 'Surat-surat'), ('Jadwal Kegiatan', 'Jadwal Kegiatan'), ('Absensi', 'Absensi'), ('Keuangan', 'Keuangan')], max_length=50),
        ),
        migrations.AlterField(
            model_name='menu',
            name='nama',
            field=models.CharField(choices=[('Panitia Utama', 'Panitia Utama'), ('Panitia IPM', 'Panitia IPM'), ('Koordinator Kelompok', 'Koordinator Kelompok'), ('Petugas Upacara', 'Petugas Upacara'), ('Panitia Pelaksana', 'Panitia Pelaksana'), ('Daftar Kelompok', 'Daftar Kelompok'), ('Pengumuman', 'Pengumuman'), ('Logistik', 'Logistik'), ('Surat-surat', 'Surat-surat'), ('Jadwal Kegiatan', 'Jadwal Kegiatan'), ('Absensi', 'Absensi'), ('Keuangan', 'Keuangan')], max_length=50, unique=True),
        ),
    ]
