# Generated by Django 5.2.4 on 2025-07-13 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panitia', '0015_alter_aksesmenu_menu_alter_menu_nama'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agenda',
            options={'ordering': ['urutan']},
        ),
    ]
