# Generated by Django 5.2.4 on 2025-07-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panitia', '0016_alter_agenda_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PanitiaUtama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabatan', models.CharField(max_length=100)),
                ('anggota', models.TextField(help_text='Masukkan satu nama per baris')),
                ('kedudukan', models.PositiveIntegerField(default=99)),
            ],
        ),
        migrations.CreateModel(
            name='PetugasUpacara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabatan', models.CharField(max_length=100)),
                ('anggota', models.TextField(help_text='Masukkan satu nama per baris')),
                ('kedudukan', models.PositiveIntegerField(default=99)),
            ],
        ),
    ]
