# Generated by Django 5.2.4 on 2025-07-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panitia', '0017_panitiautama_petugasupacara'),
    ]

    operations = [
        migrations.CreateModel(
            name='KoordinatorKelompok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelompok', models.CharField(max_length=100)),
                ('koordinator', models.TextField()),
                ('waktu', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Koordinator Kelompok',
                'verbose_name_plural': 'Koordinator Kelompok',
                'ordering': ['kelompok'],
            },
        ),
    ]
