# Generated by Django 5.2.4 on 2025-07-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panitia', '0018_koordinatorkelompok'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.IntegerField(choices=[(1, 'Hari 1'), (2, 'Hari 2')])),
                ('waktu', models.CharField(max_length=50)),
                ('plan_a', models.TextField()),
                ('plan_b', models.TextField()),
                ('urutan', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['hari', 'urutan'],
                'unique_together': {('hari', 'urutan')},
            },
        ),
    ]
